# Generated by Django 5.0.6 on 2024-06-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0004_alter_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
