# Generated by Django 3.2.3 on 2024-06-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20220104_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
