# Generated by Django 4.2.5 on 2024-07-17 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0006_booknumber_book_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booknumber",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Characters",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=20)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="demo.book"
                    ),
                ),
            ],
        ),
    ]
