# Generated by Django 4.2.5 on 2024-07-17 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0007_alter_booknumber_id_characters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characters",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characters",
                to="demo.book",
            ),
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("surname", models.CharField(max_length=30)),
                ("books", models.ManyToManyField(to="demo.book")),
            ],
        ),
    ]
