# Generated by Django 4.2.5 on 2024-08-06 01:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ratings",
            old_name="start",
            new_name="starts",
        ),
    ]
