# Generated by Django 4.2.5 on 2024-08-06 01:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_start_ratings_starts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ratings",
            old_name="starts",
            new_name="stars",
        ),
    ]
